name: st-multiverse
version: '1.11'
main: fun.spmc.STMultiverse
api-version: '1.20'
softdepend: ['Multiverse-Core', 'Vault']
commands:
  island:
    description: island cmd
  coop:
    description: coop cmd