name: st-multiverse
version: '1.12'
main: fun.spmc.stmultiverse.STMultiverse
api-version: '1.20'
softdepend: ['Multiverse-Core', 'Vault']
commands:
  island:
    description: island cmd
  coop:
    description: coop cmd
  isa:
    description: island admin cmd
  visit:
    description: visit cmd
  hub:
    description: hub cmd
  lobby:
    description: hub cmd